<?php $post = $this->postForm; ?>
<?php $post->prepare(); ?>

<style>
label {
    margin-right: 20px;
    margin-left: 20px;
    margin-bottom: 10px;
    width: 20%;
}
dt {
    width: 100%;
}
.left-side {
    float: left;
    width: 50%;
}
.right-side {
    float: right;
    width: 50%;
}
.full-width {
    float: left;
    width: 100%;
}
</style>

<!-- start of actual content -->

<h1>Online Market Posting</h1>
<hr />

<?php if ($this->flashMessenger()->hasMessages()) : ?>
    <h3 style="color:red;">Messages</h3>
    <?=  $this->htmlList($this->flashMessenger()->getMessages()); ?>
<?php endif; ?>
<?php if ($this->invalid) : ?>
    <h3 style="color:red;">Invalid Fields</h3>
    Raw error messages coming directly from the validators, not the <em>Input</em> classes.
    <ul>
    <?php foreach ($this->postForm->getInputFilter()->getInvalidInput() as $input) : ?>
        <li>
            <?= $input->getName() . ':' ?>
            <?php foreach ($input->getValidatorChain()->getValidators() as $chain) : ?>
            <?php foreach ($chain as $validator) : ?>
                <?php if ($validator && is_object($validator)) : ?>
                <?php $error = $validator->getMessages(); ?>
                    <?= implode(',', $error); ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endforeach; ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <?=  '<hr />'  ?>
<?php endif; ?>

<?php echo $this->form()->openTag($post); ?>
<?php echo $this->formCollection($post); ?>
<?php echo $this->form()->closeTag(); ?>
