<h1>Online Market</h1>
<table>
    <tr><th>Tomorrow</th><td width="10%">&nbsp;</td><td><?= $this->tomorrow ?></td></tr>
    <tr><th>Next Week</th><td width="10%">&nbsp;</td><td><?= $this->week ?></td></tr>
    <tr><th>Next Month</th><td width="10%">&nbsp;</td><td><?= $this->month ?></td></tr>
</table>
<b>TEST:</b> <?= $this->test; ?>
<h3>Categories</h3>
<?= $this->leftLinks($this->categories, '/market/view/categories'); ?>
